[2020-06-18 02:32:01,121] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: file_sensor_test_v2.retrain_model 2020-06-17T00:05:00+00:00 [queued]>
[2020-06-18 02:32:01,164] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: file_sensor_test_v2.retrain_model 2020-06-17T00:05:00+00:00 [queued]>
[2020-06-18 02:32:01,165] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 02:32:01,165] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 02:32:01,165] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 02:32:01,185] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): retrain_model> on 2020-06-17T00:05:00+00:00
[2020-06-18 02:32:01,190] {standard_task_runner.py:53} INFO - Started process 69777 to run task
[2020-06-18 02:32:01,355] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: file_sensor_test_v2.retrain_model 2020-06-17T00:05:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-06-18 02:32:01,397] {logging_mixin.py:112} INFO - hi
[2020-06-18 02:32:01,400] {python_operator.py:114} INFO - Done. Returned value was: it worked
[2020-06-18 02:32:01,423] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=file_sensor_test_v2, task_id=retrain_model, execution_date=20200617T000500, start_date=20200618T063201, end_date=20200618T063201
[2020-06-18 02:32:11,055] {logging_mixin.py:112} INFO - [2020-06-18 02:32:11,054] {local_task_job.py:103} INFO - Task exited with return code 0
