[2020-06-12 10:44:44,844] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: file_sensor_test_v1.predict_model 2020-06-11T03:10:00+00:00 [queued]>
[2020-06-12 10:44:44,863] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: file_sensor_test_v1.predict_model 2020-06-11T03:10:00+00:00 [queued]>
[2020-06-12 10:44:44,863] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 10:44:44,864] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-12 10:44:44,864] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 10:44:44,874] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): predict_model> on 2020-06-11T03:10:00+00:00
[2020-06-12 10:44:44,877] {standard_task_runner.py:53} INFO - Started process 24020 to run task
[2020-06-12 10:44:44,980] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: file_sensor_test_v1.predict_model 2020-06-11T03:10:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-06-12 10:44:45,566] {taskinstance.py:1145} ERROR - local variable 'model' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/owner/airflow/dags/gen_model.py", line 40, in predict
    model = model.load_model("games.h5")
UnboundLocalError: local variable 'model' referenced before assignment
[2020-06-12 10:44:45,568] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-12 10:44:54,820] {logging_mixin.py:112} INFO - [2020-06-12 10:44:54,818] {local_task_job.py:103} INFO - Task exited with return code 1
